"""
Session and admin token stores for Trove.

Provides ExpirableTokenDict — a thread-safe, self-cleaning token registry —
and two module-level singletons used throughout the application:

  session_store — short-lived tokens for all connected clients (2 h sliding TTL)
  admin_store   — longer-lived tokens for authenticated admin sessions (8 h sliding TTL)
"""
import secrets
import threading
import time
from datetime import datetime, timedelta


class ExpirableTokenDict:
    """
    Thread-safe in-memory token registry with sliding expiry.

    Each token is a URL-safe random string generated by secrets.token_urlsafe.
    On every successful validate_and_refresh() call the token's expiry is
    pushed forward by the configured TTL. A background daemon thread sweeps
    out expired entries at the configured interval.
    """

    def __init__(self, ttl: timedelta, sweep_interval: timedelta) -> None:
        """
        Args:
            ttl: How long a token lives after its last use.
            sweep_interval: How often the background sweep runs.
        """
        self._ttl = ttl
        self._tokens: dict[str, datetime] = {}
        self._lock = threading.Lock()
        t = threading.Thread(
            target=self._sweep_loop,
            args=(sweep_interval,),
            daemon=True,  # Dies with the process; no lifespan management needed.
        )
        t.start()

    def create(self) -> str:
        """Generate a new URL-safe token, store it with expiry now+TTL, and return it."""
        token = secrets.token_urlsafe(32)
        with self._lock:
            self._tokens[token] = datetime.now() + self._ttl
        return token

    def validate_and_refresh(self, token: str) -> bool:
        """
        Return True if the token exists and has not expired; extend its TTL.

        Returns False if the token is unknown or its expiry has passed.
        On a True result the expiry is reset to now + TTL (sliding window).
        """
        with self._lock:
            expiry = self._tokens.get(token)
            if expiry is None or datetime.now() > expiry:
                return False
            self._tokens[token] = datetime.now() + self._ttl
            return True

    def revoke(self, token: str) -> None:
        """Remove a token immediately (e.g. on admin logout)."""
        with self._lock:
            self._tokens.pop(token, None)

    def clear(self) -> None:
        """Remove all tokens. Intended for test isolation."""
        with self._lock:
            self._tokens.clear()

    def _sweep(self) -> None:
        """Remove all expired entries. Called by the background thread."""
        now = datetime.now()
        with self._lock:
            expired = [t for t, exp in self._tokens.items() if now > exp]
            for t in expired:
                del self._tokens[t]

    def _sweep_loop(self, interval: timedelta) -> None:
        """Sleep for interval, then sweep. Repeats indefinitely (daemon thread)."""
        while True:
            time.sleep(interval.total_seconds())
            self._sweep()


# Module-level singletons — one per concern.
session_store = ExpirableTokenDict(
    ttl=timedelta(hours=2),
    sweep_interval=timedelta(minutes=5),
)
admin_store = ExpirableTokenDict(
    ttl=timedelta(hours=8),
    sweep_interval=timedelta(minutes=5),
)
